# Generated by Django 3.0.3 on 2020-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200219_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remind_at',
            field=models.DateTimeField(null=True, verbose_name='Remind at'),
        ),
    ]
