# Generated by Django 3.0.3 on 2020-02-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20200222_2351'),
        ('todos', '0005_auto_20200222_2040'),
    ]

    operations = [
    ]
